name: project_test
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.910+910

environment:
  sdk: '>=2.16.0 <3.0.0'
  #flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  adobe_xd: ^2.0.0+1
  google_maps_flutter: ^2.1.8
  location: ^4.4.0
  geolocator: ^8.2.0
  step_progress_indicator: ^1.0.0
  shared_preferences: ^2.0.5
  sqflite: ^2.0.0+3
  image_picker: ^0.8.4+2
  fl_chart: ^0.55.0
  http: ^0.13.3
  provider: ^6.0.1
  flutter_svg: ^1.0.3
  flutter_polyline_points: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_neat_and_clean_calendar: ^0.3.4+17
  circular_countdown: ^2.1.0
  circular_countdown_timer: ^0.2.0
  syncfusion_flutter_signaturepad: ^20.1.47
  syncfusion_flutter_pdfviewer: ^20.1.47-beta
  flutter_local_notifications: ^9.7.0
  url_launcher: ^6.1.4
  device_info_plus: ^4.0.0
  email_validator: ^2.0.1
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_database: ^9.0.16
  firebase_messaging: ^11.4.2
  cloud_firestore: ^3.1.18
  flutter_chat_ui: ^1.6.4
  flutter_chat_types: ^3.4.5
  open_file: ^3.2.1
  uuid: ^3.0.4
  mime: ^1.0.0
  webview_flutter: ^3.0.4
  rxdart: ^0.27.1
  path_provider: ^2.0.2
  wakelock: ^0.6.1+2
  flutter_firebase_chat_core: ^1.6.3
  firebase_storage: ^10.2.18
  flutter_html: ^3.0.0-alpha.2
  clipboard: ^0.1.3
  flutter_custom_tabs: ^1.0.4
  external_app_launcher: ^3.0.0
  flutter_multi_formatter: ^2.5.1  #format phone number
  pin_code_fields: ^7.3.0  #pin code
  flutter_countdown_timer: ^4.1.0
  new_version: ^0.3.0 #update version appStore playStore
  badges: ^2.0.2
  connectivity_plus: ^2.3.0
  #background_location: ^0.8.1
  background_location: 
    git:
      url: https://github.com/hilalbaig/background_location.git
      ref: master
  package_info_plus: ^1.4.2 #check Local version app
  dropdown_search: ^5.0.2
  version_check: ^0.2.1 #update version appStore playStore
  firebase_crashlytics: ^2.8.2 
  platform_device_id: ^1.0.1
  date_time_picker: ^2.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt/Prompt-Regular.ttf
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Bold-Font.ttf
        - asset: assets/fonts/Helvetica.ttf
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun/Sarabun-Bold.ttf
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
